### ISSUE TITLE
開発ルール

### ISSUE THREAD

**Issue by woshahua** [woshahua/Survival-JP#2]
## frontend
- vue (nuxt.js?)
- 不想写太多css + 方便开发 → vuetify
https://vuetifyjs.com/en/
- `master` merge后就会自动在firebase上hosting

## backend
- golang ?
- aws / gcp (firebase) ?
- API管理 ? 贴在scrapbox里面？postman?

## design
https://www.figma.com/file/PtNI8Q8odU7u6Z4FyX4CGf/%E6%97%A5%E6%9C%AC%E7%96%AB%E6%83%85%E6%8C%87%E5%8D%97?node-id=0%3A1 

## library
- 手动实现复杂的肯定用library，前端的话图表这块，server的话orm想用gorm

**Comment by nikoloside** [comment]
# frontend的概要

在这里简单介绍一下，做frontend可能会面临的问题。
还有就是我自己对前端的理解全部写一下，大家看到之后对某一块内容觉得讲错了，
或者有疑问不懂的地方可以在issue下面提问，
然后最终的解答会补充回这个document上面

## 技术构成 & 前提知识

### 需要了解的技术关键词

- 关于SSR vs SSG vs SPA， Web Application vs 服务器编译

其实如果不去讨论优越性
SSR=服务器编译出网页内容，用户下载网页内容（内容HTML 图像assets js代码），浏览器渲染
SPA=服务器编译出WebApplication，用户下载编译好的WebApplication（不包含图像assets），WebApplication动态生成浏览器渲染的内容

|--|--|--|--|
| 项目 | 优点 | 缺点 | 例子 |
|WebApplication| 刷新比较快，基本无缝，动画效果更流畅，可以做加载动画 | 初始加载比较慢（可以做个Loading界面），SEO的对应有学习成本| Gmail Facebook 机核等网站 |
|SSR| 初次页面加载比SAP快，SEO的对应比较简单粗暴 | 每次刷新慢，加载每一个页面不太舒服，不酷 | b站 亚马逊 |



- 关于HTML5和DOM 
首先HTML CSS Javascript是互联网3件套，但是这个概念随着时间变化，会有各种新的定义。

第一个要讲的比较关键的是flash这种文件格式的消失。
flash事实上是一种图形渲染器。
但是随着 【Google的jb8的实时js编译性能提高】【flash的ui 内容逻辑 代码逻辑混乱】的特性。
flash被新的技术框架淘汰。

如今
【内容结构=HTML5】
【图形UI渲染=CSS】
【代码逻辑=Javascript/Typescript】

简单说，现在的互联网设计，严格准守逻辑分离，
【Content】【UI】【Logic】尽可能会分开处理

- 关于为什么不用jquery

jquery严格意义上是，用js来做出一系列ui动画的外部图形库。
在H5的时代，基本上所有的动画都能用CSS实现。所以不再允许使用jquery。

其次是jquery严格意义上会生成很多多余的ui代码。
而H5时代，会尽可能避免使用javascript或者typescript来写页面逻辑以外的代码。

- 关于CSS和SCSS和SASS

SCSS和SASS是针对CSS的编译器。
原生的CSS不是面向对象的语言，原本的CSS不支持class的概念。
而SASS和SCSS会在编译的时候自动解决css编译的问题。
比如说当需要继承的时候，

```
// 编译前
.block {
  color:white;
  &:hover {
    color:red;  
}

// 编译后
.block{
  color:white;
}
.block:hover{
  color:red;
}
```
以前的CSS时代不允许继承，所有的定义都要重新写一遍，
而且以前的CSS不存在全局变量和Local变量的概念，基本上CSS只要加载了就是全局变量。

然后SCSS和SASS是分别两批人弄的不同语言，稍微有一些差别，
我个人比较倾向SCSS派，
还有就是SCSS必须和Webpack2-3的使用，算是Webpack提供的3件套其中之一。

- 关于Javascript和Typescript

最近Typescript是比Javascript更优秀的编译器，
毕竟Javascript因为浏览器版本编译器不可控的问题，还有就是编译效率的问题，其实还是挺烦。
而且null check以及一部分的没有型的问题非常不稳定。
虽然最终还是要Typescript->javascript->浏览器（IE Chrome Edge Fox）的J8编译器。

- 关于现代前端框架和近代前端框架 vue vs react vs angularJS vs RailsOnRuby

angularJS是Google系的前端开源
react是FB的前端开源
vuejs是前google的前端设计师（对，没错，是设计师）的开源项目。
是一个美yi华人，所以和国内的亲和度非常高，国内因为mz主义，国内大公司也比较倾向于用vue开发
这里有一个纪录片 https://www.youtube.com/watch?v=OrxmtDw4pVI

然后说到底，react个人认为是最好的，
- react的所有页面逻辑代码，不管是HTML和CSS和JS都是推荐面向对象编程的整体的解决方案
- vuejs容易上手，但是本质是一个 网页渲染器+Flux框架+[html scss js 封装包]
- AngularJS和react的理念类似，但是规约太过复杂，没有自由的灵魂

然后RailsOnRuby和PHP之前写的时候，写起来基本上是HTML生成器的感觉。
我的所有代码都是为了生成HTML，相比较于 三件套封装包 vuejs，只为了生成HTML的旧的服务器前端编译引擎，
就无法写出Web Application的概念


- 关于WebPack3-5的诞生

https://webpack.js.org/
![image](https://user-images.githubusercontent.com/19186199/103758252-49786000-5055-11eb-8101-4efb6821f4ca.png)
这幅图是比较直观说明了WebPack是什么，
因为WebPack的诞生，让SPA这个东西的优越性体现了出来。
首先WebPack是一个素材的封装数据库。
比如说代码里面的所有内容都会重新分配link，然后取消层级统一封装，

这样的封装的目的，是把HTML和图片和javascript的内容分开封装，然后给assets提供getter。
这就意味着，

内容HTML 图片assets JS/CSS → 下载页面数据 → 浏览器渲染
内容HTML JS/CSS → 下载WebApplication（WebPack） → 根据WebApplication代码，按需要读取WebPack的Source 下载图片，cs和js→ 浏览器渲染

简单说，
Webpack + SPA = 可以按照需要切换界面内容的网页端APP

初始因为要下载WebApplication的框架需要花点时间，
页面切换速度更快，
图片加载速度和SSR接近
不需要重复下载重复的库，比如说字体，header等

- 关于使用UI框架的问题，Bootstrap vs vuetify vs 原生vue的Component

上面的vuetify 和Boostrap的UI套件，简单说就是Twitter或是网络义士做好的按钮吖，滚动条吖等一系列的UI套件，
有点接近于Google或者AppleiOS的外部UI库。
h5和css接近于Android和iOS的原生UI库，所以基本上我们算是

jQuery < css+h5 < 我们自己写的原生css < vuetify

的感觉。

但是因为设计师的理念，会有许多特别的ui动作或者是customize 是处于中间的位置，
所以，理论上
是需要
从 css+h5 → 我们想要的理想效果
还是 vuetify → 我们想要的理想效果
还是有比较大的区别，

对于css + h5玩不熟的人，以及不需要customize来说，学习vuetify要更快，因为学会了之后就直接获得了
css+h5  → 怎么去Customize　→ 和vuetify差不多的ui效果
的产物。

- 关于BEM的概念

http://getbem.com/naming/
是一套css HTML js的一一对应的继承概念，
有点像是HTML CSS的コード規約，
我们的之前的网站是用这套在开发。

## 需要了解的之前的网站的例子

https://github.com/nikoloside/BitValley.COVID-19

- vue cli 2 ~~Nuxt.js~~+ 
- javascript（airbnb 的elint）~~泛用javascript ， typescript~~ +
- vue的自带SPA模版，拥有vuex和vue-router的flux框架 ~~SSR~~+
- webpack 3.0 +
- AWS的GithubHook，master里Merge之后会自动Static Hosting

## 然后我现在的前端经验能想到的最优技术框架

- vue cli 3

- TypeScript

- vuetify + 拥有GUI的UI Component库

- SPA+SEO解决方案 (SSR？)

- vue 原生Library GUI库

- AWS或者firebase的Static Hosting（每个月服务器费用50日元）

- 媒体内容
    - 文章【以Json为数据结构的前端渲染】
    - 视频【直接爬Youtube或者B站的Link】
    - .....

**Comment by woshahua** [comment]
太长了，还没看。。
我再开一个issue套路，lint和merge这块的吧
